### ISSUE TITLE
想转发多个主题到kafka怎么操作？

### ISSUE THREAD

**Issue by fuuhoo** [thousmile/go_emqx_exhook#2]
不想转发到别的插件，只是转发到kafka并且支持多个主题并重写。

**Comment by thousmile** [comment]
参考如下配置
```yaml
appName: go_emqx_exhook
port: 16565
mqType: Kafka 

# emqx 主题
bridgeRule:
  topics:
    - "/user"
    - "/test"
    - "/demo"

# kafka 配置
kafkaConfig:
  addresses:
    - 127.0.0.1:9092
  # 主题不存在，就自动创建
  topic: emqx_exhook
  # 消息压缩类型 支持: "none", "gzip", "snappy", "lz4", "zstd", 默认: "none"
  compressionCodec: none
  # 分区数量，默认 -1 
  numPartitions: 3
  # 副本数量，默认 -1 
  replicationFactor: 3

```
